# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b288bbf422666ab419a32eb03d433586ae4dbf23b7220a113123881b46b7eeba1e132938919e647da59eb0c25111d71301033a77c0b22c4beb0c403062bf5148

test:
  secret_key_base: 5a66672653a28ed82212792aa0e8aabf6807315ab0ef3c512b9fbaf2673bd0ac8125947efbd260e881fa9720829e5f47e17879dd20aff73200667f35ad921495

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
